// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_YP-u8_0dUfSkavGS3cvNTR002Kqvsoc',
    appId: '1:262265089602:web:5d406465e41663e9e7c7db',
    messagingSenderId: '262265089602',
    projectId: 'tafgenius',
    authDomain: 'tafgenius.firebaseapp.com',
    storageBucket: 'tafgenius.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_HWh8_FdCx0yhEd14nr_EzwHo55PcC48',
    appId: '1:262265089602:android:5082fcca710a6bece7c7db',
    messagingSenderId: '262265089602',
    projectId: 'tafgenius',
    storageBucket: 'tafgenius.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeqQu2S8U8lgMSwDCGfy3RYkqYGtwTi5k',
    appId: '1:262265089602:ios:3fc4a1778f7f0e50e7c7db',
    messagingSenderId: '262265089602',
    projectId: 'tafgenius',
    storageBucket: 'tafgenius.firebasestorage.app',
    iosBundleId: 'com.example.tafgeniusmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeqQu2S8U8lgMSwDCGfy3RYkqYGtwTi5k',
    appId: '1:262265089602:ios:3fc4a1778f7f0e50e7c7db',
    messagingSenderId: '262265089602',
    projectId: 'tafgenius',
    storageBucket: 'tafgenius.firebasestorage.app',
    iosBundleId: 'com.example.tafgeniusmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_YP-u8_0dUfSkavGS3cvNTR002Kqvsoc',
    appId: '1:262265089602:web:d6440c58acc69b13e7c7db',
    messagingSenderId: '262265089602',
    projectId: 'tafgenius',
    authDomain: 'tafgenius.firebaseapp.com',
    storageBucket: 'tafgenius.firebasestorage.app',
  );
}
